version: "3"
services:
  postgres:
    container_name: stashbot-db
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./postgresql/data:/var/lib/postgresql # maps host to data directory inside cont
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  service:
    container_name: stashbot_server
    build:
      context: ./service
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./service/config:/app/config
      - ./service/src:/app/src
      - ./service/test:/app/test
    # environment:
    #   DATABASE_URL: postgres://username:root@stashbot-db:5432/api
    ports:
      - "8080:8080" # port mapping: host:destination
  ui:
    container_name: stashbot_ui
    build:
      context: ./ui
      dockerfile: Dockerfile.dev  # on move to prod, update this
    volumes:
      - /app/node_modules
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ./ui/.env:/app/.env:ro
    ports:
      - "3000:3000"
  pgadmin-compose:
    container_name: stashbot_db_ui
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@test.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres
