FROM node:16-alpine

# EXPOSE 3000
RUN mkdir -p /app/public /app/src
WORKDIR /app
 #ignore if don't have react with typescript
# COPY tsconfig.json /app/tsconfig.json
#ignore if don't have react with typescript
# COPY tslint.json /app/tslint.json 
COPY package*.json ./
## install only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm install
COPY . .
RUN npm run build

CMD ["npm", "start"]